default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: ryota.murakami
  password:

development:
  <<: *default
  database: otsukimi

test:
  <<: *default
  database: otsukimi

production:
  <<: *default
  database: otsukimi
